<?php
include('date-function.php');
?>
<div class="adzan-countdown">
    <div class="opacity">
        <div class="spacer-big">
        <div class="countdown" id="js-countdown">

            <div class="countdown_item">
                <div class="countdown_timer countdown-minute" aria-labelledby="minute-countdown">
                    00
                </div>
            </div>
            <div class="countdown_item">
                <div class="spacing">
                    :
                </div>
            </div>
            <div class="countdown_item">
                <div class="countdown_timer countdown-second" aria-labelledby="second-countdown">
                </div>
            </div>
        </div>
        <div class="information">
            <div class="sholat-header">
            </div>
            <div class="sholat-footer">
            </div>
        </div>
    </div>
</div>
