<?php
?>
<div class="opacity sholat">
    <div class="clock">
        <div class="countdown_item">
            <div class="countdown_timer countdown-hour">
                12
            </div>
        </div>
        <div class="countdown_item">
            <div class="spacing">
                :
            </div>
        </div>
        <div class="countdown_item">
            <div class="countdown_timer countdown-minute">
                59
            </div>
        </div>
        <div class="countdown_item">
            <div class="spacing">
                :
            </div>
        </div>
        <div class="countdown_item">
            <div class="countdown_timer countdown-second">
                59
            </div>
        </div>
    </div>
</div>
