<?php
?>
<div class="row main-row sholat">
    <div class="overlay-full">
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="spacer-1">&nbsp;</div>
        <div class="clock clock-wrap clock-wrap-large">
            <div class="hour-wrap">
                <div class="digit-top">
                <div class="front">12</div>
                <div class="back">12</div>
                </div>
                <div class="digit-bottom">
                <div class="front">12</div>
                </div>
            </div>
            <div class="min-wrap">
                <div class="digit-top">
                <div class="front">12</div>
                <div class="back">24</div>
                </div>
                <div class="digit-bottom">
                <div class="front">12</div>
                </div>
            </div>
            <div class="sec-wrap">
                <div class="digit-top">
                <div class="front">12</div>
                <div class="back">24</div>
                </div>
                <div class="digit-bottom">
                <div class="front">12</div>
                </div>
            </div>
        </div>

    </div>
</div>
