<?php

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title></title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Clock -->
        <link href="css/clock.css" type="text/css" rel="stylesheet">

        <!-- Slick Carousel -->
        <link href="css/slick.css" type="text/css" rel="stylesheet">

        <!-- <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'> -->

        <!-- Specific -->
        <link href="css/style.css" type="text/css" rel="stylesheet">
    </head>
    <body>


        <div id="content-container" class="background-full full">
        </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery-1.12.0.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/moment.min.js"></script>
    <script src="js/moment-range.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.animate-enhanced.min.js"></script>
    <script src="js/slick.min.js"></script>
    <script src="js/jquery.marquee.min.js"></script>

    <script src="js/sound.js"></script>


    <script>
    $(function() {

        // Get shalat times

        /*
        $.ajax({
                url: '/sholat-time',
                type: 'get',
                dataType: 'json',
                async: false,
                success: function(data) {
                    sholat_time = data;
                }
        });
        */

        var sholat_time = jQuery.parseJSON( '[ {"name":"subuh","time":"2017-10-11 19:37:14","fine_tune":["1","1","2","1"]} ]' );

        setInterval(function() {

            var currentSholat = "";
            $(sholat_time).each( function(i, j) {
                var check_time = moment(j.time);

                // Let's check if there's fine_tune variable
                // If not. set default values
                if (j.fine_tune === null) {
					var iqamatTime = 10; // Default iqamat time (m)
					var sholatDuration = 10; // Default sholat duration (m)
					var prepareDuration = 5; // Default preparation time (m)
					var totalDuration = iqamatTime + sholatDuration;
				}

				else {
					var iqamatTime = parseInt(j.fine_tune[2]);
					var sholatDuration = parseInt(j.fine_tune[3]);
					var prepareDuration = parseInt(j.fine_tune[0]);
					var totalDuration = iqamatTime + sholatDuration;
				}

                var maxTime = moment().add(prepareDuration,'m').format('YYYY-MM-DD HH:mm:ss'); // Before azan
                var minTime = moment().subtract((totalDuration),'m').format('YYYY-MM-DD HH:mm:ss'); // After azan
                if (check_time.isBetween(minTime, maxTime)) {
                    currentSholat = {'name': j.name, 'time': j.time, 'iqamat': iqamatTime};
                }
                console.log(currentSholat);
            });


            if (typeof(currentSholat) == 'object')
            {
                var ref_time = moment(currentSholat.time);

                var enterSholatTime = moment(ref_time).format('YYYY-MM-DD HH:mm:ss');
                var endAdzan = moment(ref_time).add(1, 'm').format('YYYY-MM-DD HH:mm:ss');
                // var callIqamat = moment(ref_time).add(3, 'm').format('YYYY-MM-DD HH:mm:ss');
                var callIqamat = moment(ref_time).add(currentSholat.iqamat, 'm').format('YYYY-MM-DD HH:mm:ss');

                // Adzan countdown
                if (moment().isBefore(enterSholatTime))
                {

                    // Request adzan-countdown content
                    if ( ! $('#content-container').find('.adzan-countdown').length)
                    {
                        console.log('request adzan-countdown content');
                        $.ajax({
                                url: '/adzan-countdown',
                                type: 'get',
                                dataType: 'html',
                                async: false,
                                success: function(data) {
                                    // sholat_time = jQuery.parseJSON(data);
                                    $(' #content-container ').html(data);
                                    var sholatName = currentSholat.name;
                                    var sholatHeader = "Menuju waktu Adzan";
                                    $('.sholat-header').html(sholatHeader);
                                    var sholatFooter = "Sholat " + sholatName[0].toUpperCase() + sholatName.slice(1);
                                    $('.sholat-footer').html(sholatFooter);

                                    $('.adzan-countdown').find('.'+currentSholat.name).addClass('success').find('span').addClass('current-prayer');

                                    var durationCountDown = moment(enterSholatTime).diff(moment(), 'seconds');
                                    var message = 'Countdown to Adzan ' + sholatName + ' ' + durationCountDown;

                                    var minWrap = $(' .adzan-countdown ').find('.min-wrap');
                                    var minFront = minWrap.find('div.front');

                                    var secWrap = $(' .adzan-countdown ').find('.sec-wrap');
                                    var secFront = secWrap.find('div.front');


                                    var currentMin = 0;
                                    var currentSec = 0;
                                    var duration = durationCountDown;
                                    var timer = duration, min, sec;
                                    var adzanCountdown = setInterval(function()
                                    {
                                        // Countdown
                                        min = parseInt(timer / 60, 10);
                                        sec = parseInt(timer % 60, 10);

                                        if (--timer < 0) {
                                            timer = duration;
                                        }

                                        if (currentMin != min)
                                        {
                                            currentMin = min;
                                            var minText = min < 10 ? '0' + min : min;
                                            minFront.html(minText);
                                        }
                                        if (currentSec != sec)
                                        {
                                            currentSec = sec;
                                            var secText = sec < 10 ? '0' + sec : sec;
                                            secFront.html(secText);
                                        }

                                        // Analog clock
                                        var now = moment(),
                                            second = now.seconds() * 6,
                                            minute = now.minutes() * 6 + second / 60,
                                            hour = ((now.hours() % 12) / 12) * 360 + 90 + minute / 12;

                                        $('.analog-hour').css("transform", "rotate(" + hour + "deg)");
                                        $('.analog-minute').css("transform", "rotate(" + minute + "deg)");
                                        $('.analog-second').css("transform", "rotate(" + second + "deg)");


                                    }, 1000);


                                }
                         });
                    }

                    var durationCountDown = moment(enterSholatTime).diff(moment(), 'seconds');
                    console.log(durationCountDown);

                    // Play beep sound
                    if (durationCountDown < 15)
                    {
                        shortBeepSound.play();
                    }



                }

                // Adzan
                else if (moment().isBetween(enterSholatTime, endAdzan))
                {

                    // Request adzan content
                    if ( ! $('#content-container').find('.adzan').length)
                    {
                        console.log('request adzan content');
                        $.ajax({
                                url: '/adzan',
                                type: 'get',
                                dataType: 'html',
                                async: false,
                                success: function(data) {
                                    // sholat_time = jQuery.parseJSON(data);
                                    $(' #content-container ').html(data);

                                    var sholatName = currentSholat.name;
                                    var sholatHeader = "Saat Adzan " + sholatName[0].toUpperCase() + sholatName.slice(1);
                                    $('.current-prayer-name').html(sholatHeader);

                                }
                         });
                    }

                    console.log('Adzan');
                }

                // Iqamat countdown
                else if (moment().isBetween(endAdzan, callIqamat))
                {
                    // Request iqamat-countdown content
                    if ( ! $('#content-container').find('.iqamat-countdown').length)
                    {
                        console.log('request iqamat-countdown content');
                        $.ajax({
                                url: '/iqamat-countdown',
                                type: 'get',
                                dataType: 'html',
                                async: false,
                                success: function(data) {
                                    // sholat_time = jQuery.parseJSON(data);
                                    $(' #content-container ').html(data);
                                    var sholatName = currentSholat.name;
                                    var sholatHeader = "Sholat " + sholatName[0].toUpperCase() + sholatName.slice(1);
                                    $('.current-prayer-name').html(sholatHeader);
                                    $('.iqamat-countdown').find('.'+currentSholat.name).addClass('success').find('span').addClass('current-prayer');

                                    var durationCountDown = moment(callIqamat).diff(moment(), 'seconds');
                                    var message = 'Countdown to Iqamat '+durationCountDown;

                                    var minWrap = $(' .iqamat-countdown ').find('.min-wrap');
                                    var minFront = minWrap.find('div.front');

                                    var secWrap = $(' .iqamat-countdown ').find('.sec-wrap');
                                    var secFront = secWrap.find('div.front');

                                    // var currentHour = 0;
                                    var currentMin = 0;
                                    var currentSec = 0;
                                    var duration = durationCountDown;
                                    var timer = duration, min, sec;
                                    setInterval(function()
                                    {

                                        // Countdown
                                        min = parseInt(timer / 60, 10);
                                        sec = parseInt(timer % 60, 10);

                                        if (--timer < 0) {
                                            timer = duration;
                                        }

                                        // Play sound
                                        if (timer < 30)
                                        {
                                            // snd.play();

                                        }

                                        if (currentMin != min)
                                        {
                                            currentMin = min;
                                            var minText = min < 10 ? '0' + min : min;
                                            minFront.html(minText);
                                        }
                                        if (currentSec != sec)
                                        {
                                            currentSec = sec;
                                            var secText = sec < 10 ? '0' + sec : sec;
                                            secFront.html(secText);
                                        }

                                        // Analog clock
                                        var now = moment(),
                                            second = now.seconds() * 6,
                                            minute = now.minutes() * 6 + second / 60,
                                            hour = ((now.hours() % 12) / 12) * 360 + 90 + minute / 12;

                                        $('.analog-hour').css("transform", "rotate(" + hour + "deg)");
                                        $('.analog-minute').css("transform", "rotate(" + minute + "deg)");
                                        $('.analog-second').css("transform", "rotate(" + second + "deg)");

                                    }, 1000);
                                }
                         });
                    }

                    var durationCountDown = moment(callIqamat).diff(moment(), 'seconds');
                    console.log(durationCountDown);

                    // Play beep sound
                    if ((durationCountDown < 15) && (durationCountDown >= 5))
                    {
                        shortBeepSound.play();
                    }
                    else if (durationCountDown < 5)
                    {
                        longBeepSound.play();
                    }




                    // console.log(message);
                }

                // Sholat
                else
                {
                    // Request sholat content
                    if ( ! $('#content-container').find('.sholat').length)
                    {
                        console.log('request sholat content');
                        $.ajax({
                                url: '/sholat',
                                type: 'get',
                                dataType: 'html',
                                async: false,
                                success: function(data) {
                                    // sholat_time = jQuery.parseJSON(data);
                                    $(' #content-container ').html(data);
                                    var hourWrap = $(' .sholat ').find('.hour-wrap');
                                    var hourFront = hourWrap.find('div.front');

                                    var minWrap = $(' .sholat ').find('.min-wrap');
                                    var minFront = minWrap.find('div.front');

                                    var secWrap = $(' .sholat ').find('.sec-wrap');
                                    var secFront = secWrap.find('div.front');

                                    var currentHour = 0;
                                    var currentMin = 0;
                                    var currentSec = 0;
                                    // var iteration = 0;
                                    setInterval(function() {

                                        var time = new Date();
                                        var hour = time.getHours();
                                        var min = time.getMinutes();
                                        var sec = time.getSeconds();
                                        if (currentHour != hour)
                                        {
                                            currentHour = hour;
                                            var hourText = hour < 10 ? '0' + hour : hour;
                                            hourFront.html(hourText);

                                        }
                                        if (currentMin != min)
                                        {
                                            currentMin = min;
                                            var minText = min < 10 ? '0' + min : min;
                                            minFront.html(minText);
                                        }
                                        if (currentSec != sec)
                                        {
                                            currentSec = sec;
                                            var secText = sec < 10 ? '0' + sec : sec;
                                            secFront.html(secText);


                                        }
                                    }, 500);

                                }
                         });
                    }

                    console.log('Sholat '+currentSholat.name);
                }
            } // End if

            // Default display: Slideshow
            else
            {
                // Slideshow
                if ( ! $('#content-container').find('.slideshow').length)
                {
                    console.log('request slideshow content');
                    $.ajax({
                            url: '/slideshow',
                            type: 'get',
                            dataType: 'html',
                            async: false,
                            success: function(data) {
                                // sholat_time = jQuery.parseJSON(data);
                                $(' #content-container ').html(data);
                                $(' .slides ').slick({
                                    autoplay: true,
                                    // 10s
                                    autoplaySpeed: 10000,
                                    arrows: false,
                                    infinite: true,
                                    pauseOnHover: false,
                                    // fade: true,
                                    speed: '50',
                                    // cssEase: 'ease-in-out',

                                });

                                var hourWrap = $(' .slideshow ').find('.hour-wrap');
                                var hourFront = hourWrap.find('div.front');

                                var minWrap = $(' .slideshow ').find('.min-wrap');
                                var minFront = minWrap.find('div.front');

                                var secWrap = $(' .slideshow ').find('.sec-wrap');
                                var secFront = secWrap.find('div.front');

                                var currentHour = 0;
                                var currentMin = 0;
                                var currentSec = 0;
                                // var iteration = 0;
                                setInterval(function() {

                                    var time = new Date();
                                    var hour = time.getHours();
                                    var min = time.getMinutes();
                                    var sec = time.getSeconds();
                                    if (currentHour != hour)
                                    {
                                        currentHour = hour;
                                        var hourText = hour < 10 ? '0' + hour : hour;
                                        hourFront.html(hourText);

                                    }
                                    if (currentMin != min)
                                    {
                                        currentMin = min;
                                        var minText = min < 10 ? '0' + min : min;
                                        minFront.html(minText);
                                    }
                                    if (currentSec != sec)
                                    {
                                        currentSec = sec;
                                        var secText = sec < 10 ? '0' + sec : sec;
                                        secFront.html(secText);


                                    }
                                }, 500);

                            }
                     });
                     $(' .marquee ').marquee({
                         duration: 15000,
                         allowCss3Support: false,

                     });
                }


                console.log('Slideshow');

            }







        }, 1000);


    });

    $(document).keydown(function(e) {
        switch(e.which) {
            case 37: // left
            break;

            case 38: // up
            break;

            case 39: // right
            break;

            case 40: // down
            break;

            default: return; // exit this handler for other keys
        }
        e.preventDefault(); // prevent the default action (scroll / move caret)
    });
    </script>

    </body>
</html>
