<?php

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title></title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Clock -->
        <link href="css/clock.css" type="text/css" rel="stylesheet">

        <!-- Slick Carousel -->
        <link href="css/slick.css" type="text/css" rel="stylesheet">

        <!-- <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'> -->

        <!-- Specific -->
        <link href="css/style.css" type="text/css" rel="stylesheet">
    </head>
    <body>


        <div id="content-container" class="background-full full">
            <div class="row">
                <div class="spacer-1">&nbsp;</div>
                <div class="spacer-1">&nbsp;</div>
                <div class="col-md-6 col-md-offset-3">
                    <form action="install" method="post">
                        <div class="form-group">
                            <label for="api_token">API Token</label>
                            <input type="text" name="api_token" class="form-control" id="api_token" placeholder="API Token">
                        </div>
                        <button type="submit" class="btn btn-default">Simpan</button>
                    </form>
                </div>
            </div>
        </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery-1.12.0.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/moment.min.js"></script>
    <script src="js/moment-range.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.animate-enhanced.min.js"></script>
    <script src="js/slick.min.js"></script>
    <script src="js/jquery.marquee.min.js"></script>


    </body>
</html>
