<?php
include('date-function.php');
?>



<div class="slideshow">
    <?php
    foreach ($events as $event)
    {
        // Download image
        $filename       = basename($event->image);
        $image          = basename($image_location).'/'.$filename;
        ?>

        <img id="slide" src="<?php echo $image ?>" alt="image" />
        <?php
    }
    ?>


    <?php
    foreach ($albums as $album)
    {
        // Download image
        $filename       = basename($album->image);
        $image          = basename($album_location).'/'.$filename;
        ?>

        <img id="slide" src="<?php echo $image ?>" alt="image" />
    <?php
    }
    ?>

</div>

<div class="custom-headline">



    <?php
    foreach ($events as $event)
    {
        ?>



            <div class="content">

                <div class="header-content">
                    <div class="title"><?php echo $profil->name ?></div>
                    <div class="alamat"><?php echo $profil->address ?></div>
                </div>

                <div class="info-jumat">
                    <div class="info-title">
                        INFO SHALAT JUM'AT
                    </div>
                    <div class="info-list">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td class="text-left"><?php echo date("j-n-Y", strtotime("next Friday", strtotime($info_jumat->updated_at)))  ?></td>
                                    <td class="text-right"><?php echo $info_jumat->khatib ?></td>
                                </tr>
                                <!-- <tr>
                                    <td class="text-left">21/09/2017</td>
                                    <td class="text-right">Ust. Abdullah Gymnastiar	</td>
                                </tr>
                                <tr>
                                    <td class="text-left">21/09/2017</td>
                                    <td class="text-right">Ust. Yusuf Mansur</td>
                                </tr> -->
                            </tbody>
                        </table>
                    </div>

                </div>

                <div class="info-keuangan">
                    <div class="info-title">
                        INFO KEUANGAN MASJID
                    </div>
                    <div class="info-list">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td class="text-left">PEMASUKAN</td>
                                    <td class="text-right">Rp. <?php echo number_format($financial->income, 0, ',', '.') ?></td>
                                </tr>
                                <tr>
                                    <td class="text-left">PENGELUARAN</td>
                                    <td class="text-right">Rp. <?php echo number_format($financial->expense, 0, ',', '.') ?></td>
                                </tr>
                                <tr>
                                    <td class="text-left">SALDO</td>
                                    <td class="text-right">Rp. <?php echo number_format($financial->balance, 0, ',', '.') ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>


                <div class="isi">
                    <div class="kiri">
                        <div class="jam">
                            <?php echo date('H:i') ?>
                            <div class="hari">
                                <?php echo $indonesian_day[date('w')] ?>, <br>
                                <?php echo date('j') ?> <?php echo $indonesian_month[date('n')-1] ?> <?php echo date('Y') ?>
                            </div>
                        </div>
                    </div>
                    <div class="kanan">
                        <div class="jadwal">
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    IMSYA'
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[6]) ?>
                                </div>
                            </div>
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    SUBUH
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[0]) ?>
                                </div>
                            </div>
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    DZUHUR
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[2]) ?>
                                </div>
                            </div>
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    ASHAR
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[3]) ?>
                                </div>
                            </div>
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    MAGHRIB
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[4]) ?>
                                </div>
                            </div>
                            <div class="jadwal-shalat">
                                <div class="title-shalat">
                                    ISYA
                                </div>
                                <div class="jam-shalat">
                                    <?php echo trimSeconds($waktu_sholat[5]) ?>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        <?php

    }
    ?>

</div>

<div class="custom-marquee">
    <div class="marquee">
        <?php
        foreach ($rolling_text as $news_single)
        {
            echo "&nbsp;&nbsp;&nbsp;&nbsp;";
            echo $news_single->content;
            echo "&nbsp;&nbsp;&nbsp;&nbsp;&mdash;";
        }
        ?>
    </div>
</div>

<!--





        </div>
    </div>
    <div class="col-md-9 right-bar">
        <div class="events">
            <div class="event-slideshow">
                <div class="slides">


                </div>

                <div class="prayer-time">
                    <table class="table prayer-table">
                        <tr>
                            <?php
                            if (isset($waktu_sholat[6]))
                            {
                                ?>
                                <th class="text-center imsak"><span>Imsak<span></th>
                                <?php
                            }
                            ?>
                            <th class="text-center subuh"><span>Subuh<span></th>
                            <th class="text-center dzuhur"><span>Dzuhur</span></th>
                            <th class="text-center ashar"><span>Ashar</span></th>
                            <th class="text-center maghrib"><span>Maghrib</span></th>
                            <th class="text-center isya"><span>Isya</span></th>
                        </tr>
                        <tr>
                            <?php
                            if (isset($waktu_sholat[6]))
                            {
                                ?>
                                <td class="text-center imsak"><span><?php echo trimSeconds($waktu_sholat[6]) ?></span></td>
                                <?php
                            }
                            ?>
                            <td class="text-center subuh"><span><?php echo trimSeconds($waktu_sholat[0]) ?></span></td>
                            <td class="text-center dzuhur"><span><?php echo trimSeconds($waktu_sholat[2]) ?></span></td>
                            <td class="text-center ashar"><span><?php echo trimSeconds($waktu_sholat[3]) ?></span></td>
                            <td class="text-center maghrib"><span><?php echo trimSeconds($waktu_sholat[4]) ?></span></td>
                            <td class="text-center isya"><span><?php echo trimSeconds($waktu_sholat[5]) ?></span></td>
                        </tr>
                    </table>
                </div>


            </div>
        </div>



    </div>
</div> -->
